# Generated by Django 4.2.11 on 2024-04-16 01:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0011_remove_comentario_nome_comentario_usuario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comentario',
            name='usuario',
            field=models.CharField(choices=[('Anônimo', 'Anônimo'), ('Logado', 'Logado')], max_length=150),
        ),
    ]
